version: '3.1'
services:
    jenkins-coordinator:
        container_name: jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        image: dev/jenkins
        build:
            context: ./coordinator/
            dockerfile: Dockerfile

    jenkins-worker:
        container_name: jenkins-worker
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - jenkins-coordinator
        image: dev/jenkins-dotnetcore-agent
        build:
            context: ./worker/
            dockerfile: Dockerfile
