version: '3.1'
services:
    jenkins-coordinator:
        container_name: jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        image: dev/jenkins
        build:
            context: ./coordinator/
            dockerfile: Dockerfile
